services:
  traefik:
    image: traefik:latest
    container_name: traefik
    restart: unless-stopped
    ports:
      - 80:80
      # (Optional) Expose Dashboard
      # - 8080:8080 # Don't do this in production!
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./etc/traefik:/etc/traefik
    networks:
      - traefik
  # whoami:
  #   image: traefik/whoami:latest
  #   labels:
  #     - "traefik.enable=true"
  #     - "traefik.http.routers.whoami.rule=Host(`whoami.etiquetashopee.com.br`)"
  #     - "traefik.http.routers.whoami.entrypoints=web"
  #   networks: 
  #     - traefik

networks:
  traefik:
    external: true
