services:
  traefik:
    image: traefik:v2.9
    container_name: traefik
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
      # (Optional) Expose Dashboard
      - 8080:8080 # Don't do this in production!
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./etc/traefik:/etc/traefik
    networks:
      - traefik

  whoami:
    image: traefik/whoami
    container_name: traefik-whoami
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.whoami.entrypoints=web,websecure'
      - 'traefik.http.routers.whoami.rule=PathPrefix(`/whoami`)'
      # (Optional) TLS & Cert Resolver
      # - 'traefik.http.routers.whoami.tls=true'
      # - 'traefik.http.routers.whoami.tls.certresolver=staging'
    networks:
      - traefik

networks:
  traefik:
    external: true
